export const t = {
  title: "Éditeur page d’accueil",
  label_logo: "Logo de la recherche",
  logo_cta: "Importez votre logo",
  image_cta: "Importez une image",
  photo_member_cta: "Importez une photo",
  image_helptext: "Jpeg, png, ...",
  add_image: "Intégrer une image",
  video_url_label: "Intégrer une video",
  team_label: "Membre de l'équipe",
  partners: "Logos des partenaires",

  member_placeholder: "Nom, prénom",
  member_placeholder_2: "Fonction",
  logos_label: "Les logos des partenaires",
  logo_partner_cta: "Importer un logo",
  see_more_cta: 'Vous pouvez ajouter un onglet "à propos" pour y ajouter les informations de votre choix.',
  video_url_placeholder: "(copier ici le lien de votre vidéo)",
  logo_helptext: "png, svg max 100 ko format 60x60px",
  theme_label: "Thèmes",
  content_label: "Texte de présentation",
  title_input: "Titre de l'étude",
  title_helptext: "50 signes max",
  subtitle_input: "Sous-titre de l'étude",
  subtitle_helptext: "100 signes max",
  cta_participate: "Je participe",
  cta_show_more: 'Éditer la section "À propos"',
  cta_save: "Enregistrer",
  credits: "Ce site a été crée avec Process",
};
